---
commitizen:
  changelog_file: CHANGELOG.md
  changelog_incremental: true
  name: cz_conventional_commits
  tag_format: $major.$minor.$patch
  update_changelog_on_bump: true
  version: 0.1.3
  version_files:
  - VERSION
